Translate README
hjaremko/cute-animals pull request #186
Opened 2020-09-16 10:38 UTC by hjaremko

Close #185

2020-09-17 14:12 UTC, lsereda approved these changes
LGTM

2020-09-17 14:37 UTC, seqre requested changes

2020-09-17 14:37 UTC, seqre commented on README.md
> +Full description of available command can be found in the *Documentation* section.
```suggestion
Full list of available commands is in the *Documentation* section.
```

2020-09-17 14:37 UTC, seqre commented on README.md
> +(e.g. conversation, fight), collecting items.
```suggestion
1. The player goes through successive locations where he has the opportunity to explore, interact with other characters (e.g. conversation, fight), and collect items.
```
I'm also not sure whether there should be a comma before where

2020-09-17 14:37 UTC, seqre commented on README.md
> +(depending on the item: for combat, defense, or increasing a given attribute)
```suggestion
(depending on the item: for combat, defense, or to increase a given attribute)
```

2020-09-17 14:37 UTC, seqre commented on README.md
> +`SPRING_PROFILES_ACTIVE` : `dev`
I think we should point out there is `dev` and `prod` environment

2020-09-17 14:37 UTC, seqre commented on README.md
> +can be found in [artifacts](https://github.com/hjaremko/cute-animals/actions).
```suggestion
are in [artifacts](https://github.com/hjaremko/cute-animals/actions).
```

2020-09-17 14:37 UTC, seqre commented on README.md
> +- ```stats``` - lists character statistics
```suggestion
- ```stats``` - lists the character's statistics  
```
For consistency's sake

2020-09-17 14:37 UTC, seqre commented on README.md
> +- ```attack``` - takes a turn in combat mode
```suggestion
- ```attack``` - allows you to attack in combat mode 
```

2020-09-28 21:20 UTC, seqre approved these changes
LGTM

2020-09-28 21:22 UTC, merged